CREATE TABLE [dbo].[Homework_Tag](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TagId] [int] NOT NULL,
	[HomeworkId] [int] NOT NULL,
 CONSTRAINT [PK_HOMEWORK_TAG] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Homework_Tag]  WITH CHECK ADD  CONSTRAINT [Homework_Tag_fk0] FOREIGN KEY([TagId])
REFERENCES [dbo].[Tag] ([Id])
ON UPDATE NO ACTION
GO

ALTER TABLE [dbo].[Homework_Tag] CHECK CONSTRAINT [Homework_Tag_fk0]
GO

ALTER TABLE [dbo].[Homework_Tag]  WITH CHECK ADD  CONSTRAINT [Homework_Tag_fk1] FOREIGN KEY([HomeworkId])
REFERENCES [dbo].[Homework] ([Id])
ON UPDATE NO ACTION
GO

ALTER TABLE [dbo].[Homework_Tag] CHECK CONSTRAINT [Homework_Tag_fk1]
GO

ALTER TABLE [dbo].[Homework_Tag] 
ADD CONSTRAINT UC_HomeworkId_TagId UNIQUE(HomeworkId, TagId)
GO