CREATE TABLE [dbo].[Attendance](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LessonId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
	[IsAbsent] [bit] NOT NULL,
	[ReasonOfAbsence] nvarchar(max) DEFAULT null,
 CONSTRAINT [PK_ATTENDANCE] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UC_LessonId_UserId] UNIQUE NONCLUSTERED 
(
	[LessonId] ASC,
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Attendance]  WITH CHECK ADD  CONSTRAINT [Attendance_fk0] FOREIGN KEY([LessonId])
REFERENCES [dbo].[Lesson] ([Id])
ON UPDATE NO ACTION
GO

ALTER TABLE [dbo].[Attendance] CHECK CONSTRAINT [Attendance_fk0]
GO

ALTER TABLE [dbo].[Attendance]  WITH CHECK ADD  CONSTRAINT [Attendance_fk1] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
ON UPDATE NO ACTION
GO

ALTER TABLE [dbo].[Attendance] CHECK CONSTRAINT [Attendance_fk1]
GO

ALTER TABLE [dbo].[Attendance]
ADD CONSTRAINT UC_Attendance_LessonId_UserId UNIQUE(LessonId, UserId)
GO