CREATE TABLE [dbo].[Teacher_Group](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[GroupID] [int] NOT NULL,
 CONSTRAINT [PK_TEACHER_GROUP] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Teacher_Group]  WITH CHECK ADD  CONSTRAINT [Teacher_Group_fk0] FOREIGN KEY([UserID])
REFERENCES [dbo].[User] ([Id])
ON UPDATE NO ACTION
GO

ALTER TABLE [dbo].[Teacher_Group] CHECK CONSTRAINT [Teacher_Group_fk0]
GO

ALTER TABLE [dbo].[Teacher_Group]  WITH CHECK ADD  CONSTRAINT [Teacher_Group_fk1] FOREIGN KEY([GroupID])
REFERENCES [dbo].[Group] ([Id])
ON UPDATE NO ACTION
GO

ALTER TABLE [dbo].[Teacher_Group] CHECK CONSTRAINT [Teacher_Group_fk1]
GO

ALTER TABLE [dbo].[Teacher_Group] 
ADD CONSTRAINT UC_UserID_GroupID UNIQUE(UserID,GroupID)
GO