CREATE TABLE [dbo].[Lesson_Theme](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ThemeID] [int] NOT NULL,
	[LessonID] [int] NOT NULL,
 CONSTRAINT [PK_LESSON_THEME] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Lesson_Theme]
ADD CONSTRAINT UC_LessonTheme_LessonId_ThemeId UNIQUE(LessonId, ThemeId)
GO
