CREATE TABLE [dbo].[GroupStatus](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL
	CONSTRAINT [PK_GROUPSTATUS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF,
	STATISTICS_NORECOMPUTE = OFF, 
	IGNORE_DUP_KEY = OFF,
	ALLOW_ROW_LOCKS = ON,
	ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]