CREATE TABLE [dbo].[Material_Tag](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TagId] [int] NOT NULL,
	[MaterialId] [int] NOT NULL,
 CONSTRAINT [PK_MATERIAL_TAG] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Material_Tag]  WITH CHECK ADD  CONSTRAINT [Material_Tag_fk0] FOREIGN KEY([TagId])
REFERENCES [dbo].[Tag] ([Id])
ON UPDATE NO ACTION
GO

ALTER TABLE [dbo].[Material_Tag] CHECK CONSTRAINT [Material_Tag_fk0]
GO

ALTER TABLE [dbo].[Material_Tag]  WITH CHECK ADD  CONSTRAINT [Material_Tag_fk1] FOREIGN KEY([MaterialId])
REFERENCES [dbo].[Material] ([Id])
ON UPDATE NO ACTION
GO

ALTER TABLE [dbo].[Material_Tag] CHECK CONSTRAINT [Material_Tag_fk1]
GO

ALTER TABLE [dbo].[Material_Tag] 
ADD CONSTRAINT UC_MaterialId_TagId_Script UNIQUE(MaterialId, TagId)
GO