CREATE TABLE [dbo].[HomeworkAttemptStatus](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_HOMEWORKATTEMPTSTATUS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC)
	WITH (
	PAD_INDEX = OFF,
	STATISTICS_NORECOMPUTE = OFF, 
	IGNORE_DUP_KEY = OFF, 
	ALLOW_ROW_LOCKS = ON, 
	ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ__Homework__737584F663B15C78] UNIQUE NONCLUSTERED 
(
	[Name] ASC)
	WITH (
	PAD_INDEX = OFF,
	STATISTICS_NORECOMPUTE = OFF,
	IGNORE_DUP_KEY = OFF,
	ALLOW_ROW_LOCKS = ON,
	ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
