CREATE TABLE [dbo].[Course_Theme](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CourseID] [int] NOT NULL,
	[ThemeID] [int] NOT NULL,
 CONSTRAINT [PK_COURSE_THEME] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF,
STATISTICS_NORECOMPUTE = OFF,
IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON
--, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Course_Theme]  WITH CHECK ADD  CONSTRAINT [Course_Theme_fk0] FOREIGN KEY([CourseID])
REFERENCES [dbo].[Course] ([Id])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[Course_Theme] CHECK CONSTRAINT [Course_Theme_fk0]
GO

ALTER TABLE [dbo].[Course_Theme]  WITH CHECK ADD  CONSTRAINT [Course_Theme_fk1] FOREIGN KEY([ThemeID])
REFERENCES [dbo].[Theme] ([Id])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[Course_Theme] CHECK CONSTRAINT [Course_Theme_fk1]
GO

ALTER TABLE [dbo].[Course_Theme]
ADD CONSTRAINT UC_CourseTheme_CourseId_ThemeId UNIQUE(CourseId, ThemeId)
GO