CREATE TABLE [dbo].[Homework_Group](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[GroupId] [int] NOT NULL,
	[HomeworkId] [int] NOT NULL,
 CONSTRAINT [PK_HOMEWORK_GROUP] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UC_HomeworkId_GroupId] UNIQUE NONCLUSTERED 
(
	[HomeworkId] ASC,
	[GroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Homework_Group]  WITH CHECK ADD  CONSTRAINT [Homework_Group_fk0] FOREIGN KEY([GroupId])
REFERENCES [dbo].[Group] ([Id])
GO

ALTER TABLE [dbo].[Homework_Group] CHECK CONSTRAINT [Homework_Group_fk0]
GO

ALTER TABLE [dbo].[Homework_Group]  WITH CHECK ADD  CONSTRAINT [Homework_Group_fk1] FOREIGN KEY([HomeworkId])
REFERENCES [dbo].[Homework] ([Id])
GO

ALTER TABLE [dbo].[Homework_Group] CHECK CONSTRAINT [Homework_Group_fk1]
GO